<?php
	$level="../";
	include($level."config.php");
	include($level.Content."data-admin-taikhoan.php");
	$_isMeoVat=false;
	$_isSanPham=false;
	$_isTinTuc=false;
	$_isTaiKhoan=true;
	include($level.PAGE."layout-admin.php");
?>
